services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost/api/v1
    networks:
      - deepq-network

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:SifraNekaZaBazu123@database-deepq-demo-1.cb6os2kiyuk4.us-east-1.rds.amazonaws.com:5432/deepq
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    networks:
      - deepq-network



networks:
  deepq-network:
    driver: bridge
