services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost/api/v1
    networks:
      - deepq-network

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:SifraNekaZaBazu123@database-deepq-demo-1.cb6os2kiyuk4.us-east-1.rds.amazonaws.com:5432/deepq
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    networks:
      - deepq-network
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deepq
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - deepq-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s


networks:
  deepq-network:
    driver: bridge

volumes:
  postgres_data:
